version: 0.0
os: linux

files:             
  - source: ./webapp
    destination: /webapp

hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
   - location: ./applicationStart.sh
     timeout: 15
     runas: centos
