# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
          - image: circleci/node:7.10
        working_directory: ~/repo/webapp

        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run: yarn install

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run: yarn test
            - run:
                name: Install packages
                command: sudo apt-get update && sudo apt-get install wget zip unzip python2.7 python-pip -y
            - run:
                name: Install awscli
                command: sudo pip install awscli
            - run:
                name: Setting Signature Version 4 for S3 Request Authentication
                command: aws configure set default.s3.signature_version s3v4
            - run:
                name: zip project
                command: zip -r csye6225-codedeploy-${CIRCLE_BUILD_NUM}.zip * .[^.]*
            - run:
                name: see all files
                command: ls -al
            - run:
                name: Upload to S3 Bucket
                command: aws s3 cp csye6225-codedeploy-${CIRCLE_BUILD_NUM}.zip s3://${BUCKET_NAME}
            - run:
                name: Amazon Deploy
                command: aws deploy create-deployment --application-name csye6225-webapp --deployment-group-name csye6225-webapp-deployment --s3-location bucket=${BUCKET_NAME},bundleType=zip,key=csye6225-codedeploy-${CIRCLE_BUILD_NUM}.zip

