# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
          - image: circleci/node:7.10
        working_directory: ~/repo/webapp

        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run: yarn install

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run: yarn test
            - run:
                name: Install aws cli
                command: sudo apt-get -y -qq install awscli
            - run:
                name: Setting Signature Version 4 for S3 Request Authentication
                command: aws configure set default.s3.signature_version s3v4
            - run:
                name: Deploy to S3
                command: aws --region us-east-1 s3 sync dist s3://code-depoy.csye6225-spring2019-hera.me/ --delete